name: Update GitHub Stats Images

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:  # Manual run support

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone GitHub Readme Stats
        run: |
          git clone https://github.com/anuraghazra/github-readme-stats.git stats
          cd stats
          npm install

      - name: Generate SVGs using token
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          mkdir -p generated
          cd stats
          curl "http://localhost:3000/api?username=SiwenLi666&count_private=true&show_icons=true&theme=tokyonight" > ../generated/stats.svg
          curl "http://localhost:3000/api/top-langs?username=SiwenLi666&count_private=true&layout=compact&theme=tokyonight" > ../generated/top-langs.svg

      - name: Commit generated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated/
          git commit -m "Update GitHub stats images" || echo "No changes to commit"
          git push
