name: Update GitHub Stats Images

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 3 AM UTC
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p generated

      - name: Download GitHub Stats SVGs
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
            "https://github-readme-stats.vercel.app/api?username=SiwenLi666&count_private=true&show_icons=true&theme=tokyonight" \
            --output generated/stats.svg

          curl -H "Authorization: token $GH_TOKEN" \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=SiwenLi666&count_private=true&layout=compact&theme=tokyonight" \
            --output generated/top-langs.svg

      - name: Commit changes with PAT
        env:
          GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated/
          git commit -m "Update GitHub stats images" || echo "No changes to commit"
          git remote set-url origin https://SiwenLi666:${GH_TOKEN}@github.com/SiwenLi666/SiwenLi666.git
          git push origin main

